(load "~/.emacs.d/settings.el")
(load "~/.emacs.d/ui.el")
(load "~/.emacs.d/packages.el")
(load "~/.emacs.d/hooks.el")
(load "~/.emacs.d/keybindings.el")
(load "~/.emacs.d/xmake.el")
(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")

(require 'eaf)
(require 'eaf-markdown-previewer)
(require 'eaf-file-manager)
(require 'eaf-browser)
(require 'eaf-file-browser)

;; Others conf
(counsel-mode)
(desktop-environment-mode)
(doom-modeline-mode 1)
(evil-mode)
(global-display-line-numbers-mode)
(ivy-mode 1)
(ivy-rich-mode 1)
(savehist-mode)
(smartparens-global-mode t)
(solaire-global-mode +1)
(toggle-frame-fullscreen)
(vertico-mode 1)
(vertico-posframe-mode 1)
(yas-global-mode 1)
(pdf-tools-install)
(pdf-loader-install)
(display-battery-mode 1)
(nyan-mode 1)
