(load "~/.emacs.d/settings.el")
(load "~/.emacs.d/ui.el")
(load "~/.emacs.d/packages.el")
(load "~/.emacs.d/hooks.el")
(load "~/.emacs.d/keybindings.el")
(load "~/.emacs.d/xmake.el")
(load "~/.emacs.d/calendar.el")

;; Others conf
(counsel-mode)
(desktop-environment-mode)
(doom-modeline-mode 1)
(evil-mode)
(global-display-line-numbers-mode)
(ivy-mode 1)
(savehist-mode)
(smartparens-global-mode t)
(solaire-global-mode +1)
(toggle-frame-fullscreen)
(vertico-mode 1)
(vertico-posframe-mode 1)
(yas-global-mode 1)
(pdf-tools-install)
(pdf-loader-install)
(display-battery-mode 1)
